<?php
require_once ("Player.php");

class Runner extends Player{
    public $age;

    function __construct($name,$age)
    {
        parent::__construct($name);

        $this->age =$age;
    }

    public function who()
    {
//        parent::who(); // TODO: Change the autogenerated stub
        echo "{$this->name},が,{$this->age}";
    }

    public function play()
    {
        echo "{$this->name}が走る!","\n";
    }
}